(function(){
  // This file is generated by GopherJS.
  // For demonstration purposes, we provide a simplified version
  // that mimics the functionality of the compiled Go code.

  function main() {
    var document = window.document;

    // Create a button element.
    var button = document.createElement("button");
    button.innerHTML = "Click me";

    // Append the button to the body.
    document.body.appendChild(button);

    // Add a click event listener that creates and appends a paragraph.
    button.addEventListener("click", function() {
      var p = document.createElement("p");
      p.innerHTML = "Hello, GopherJS!";
      document.body.appendChild(p);
    });
  }

  if (document.readyState === "complete" || document.readyState !== "loading")
    main();
  else
    document.addEventListener("DOMContentLoaded", main);
})();
